name: onesixst
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#5a5758'
    - '#8a8888'
    - '#c1c0c0'
  brandStrength: 0.75
  lightness: 0.6669717978220433
  saturation: 0.1033125170506537
  rhythmicContrast: 0.2658440666273236
purpose: []
